# workflow name
name: CI

# on events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# jobs to run
jobs:

  # job 1: test go module
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      
      # step 2: checkout repository code
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2

      # step 3: install dependencies
      - name: Install all Go dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      
      # Run vet & lint on the code
      - name: Run vet & lint
        run: |
          go vet .
          golint .

  run-demo:
    name: Run Demo Application
    needs: build
    runs-on: ubuntu-latest
    steps:
      
      # step 1: set up go
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      
      # step 2: checkout repository code
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2

      # step 3: install dependencies
      - name: Install all Go dependencies
        run: go get
      
      # step 4: run demo
      - name: go run
        run: go run ./demo/calculator-demo.go

