# workflow name
name: release

# on events
on:
  release:
    types:
      - created

# jobs
jobs:
  # generate build cross-platform build files
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate build files
        uses: assadobaid/dockeraction@v1
        with:
          platforms: "linux/amd64, darwin/amd64, windows/amd64"
          package: "program"
          name: "math"
          dest: "dist"
